[pkgs]
php = "8.0"
apache = true

[config]
start = "apache2-foreground"

[setup]
postBuild = '''
echo "ServerName digitalnidom2.up.railway.app" >> /etc/apache2/apache2.conf
a2enmod rewrite
'''

[files]
/etc/apache2/sites-available/000-default.conf = """
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    <Directory /var/www/html/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
"""
